### ISSUE TITLE
Click Librarie dosnt seem to get recognized

### ISSUE THREAD

**Issue by Fdr3iZzz** [Dniel97/MQA-identifier-python#1]
Hey, idk why but it seems like your program dosnt work for me because the librarie "click" is not installed correctly, idk. Sadly I never really work with phython so its probably on my end sry.
Looking forward to hearing from you and I hope that we can fix that :)
-Franz

`C:\Users\Franz3>cd MQA-identifier-python

C:\Users\Franz3\MQA-identifier-python>pip3 install -r requirements.txt
Requirement already satisfied: click>=8.0.1 in c:\users\franz3\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (8.1.3)
Requirement already satisfied: mutagen>=1.45.1 in c:\users\franz3\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (1.45.1)
Requirement already satisfied: colorama in c:\users\franz3\appdata\local\programs\python\python310\lib\site-packages (from click>=8.0.1->-r requirements.txt (line 2)) (0.4.5)

C:\Users\Franz3\MQA-identifier-python>python3 mqa-identifier-python.py --fix-tags "C:/Users/Franz3/Desktop/music/Downloaded Qobuz"
Traceback (most recent call last):
  File "C:\Users\Franz3\MQA-identifier-python\mqa-identifier-python.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'`

**Comment by Dniel97** [comment]
It looks like your pip3 "command" is not linked to your python3 installation properly. Try `python3 -m pip install -r requirements.txt` inside the MQA-identifier-python folder.

**Comment by Fdr3iZzz** [comment]
That worked, thank you very much, may I know why my command is not linked to your python3 installation properly? any way to fix that so it dosnt happen in the future or is that too complicated.
Also thank you very much for that nice tool :)

**Comment by Dniel97** [comment]
This can happen if you install multiple python 3.x versions but I am not sure in your specific case. I would recommend checking your system variables and see if multiple python/pip paths exist.

**Comment by Fdr3iZzz** [comment]
ok, thank you very much :) sehr nett von dir
